# Config Version 1.7 ALPHA // Requires Levelsys 2.0 ALPHA & Main 1.7 - 1.8


# Discord Config
# The token for your discord bot. NOTE: Do not share this with anyone!
Bot_Token: 

# The prefix for the bots commands
Prefix: "!"

# Array of channels where bot commands can be sent
bot_channel: []

# Array of channels you can earn XP in
talk_channels: []


# Bot Config
# How much XP you earn per message
xp_per_message: 5

# How much XP is required per level (e.g - xp_per_level: 10 = Level 1 would require 10 xp to level up. Level 2 would require 20 xp to level up)
xp_per_level: 100

# Customise the Progress Bar emojis on the Stats Menu
completed_bar: ":blue_square:"
uncompleted_bar: ":white_large_square:"

# Array of roles you can be rewarded for levelling up. Rank for each role, in same order as level_roles
level_roles: ["test1", "test2"]
level_roles_num: [1, 2]

# Set what the bot is currently playing
bot_status_text: "📖 | Modern Levels"

# IDLE, DND, ONLINE, OFFLINE
bot_activity: online

# Admin Role for admin type commands
admin_role: "🕹️| Admin"


# Leaderboard Config
# Amount of users to be shown on the leaderboard
leaderboard_amount: 10

# Sets the image that displays on the leaderboard embed
leaderboard_image: "https://cdn.discordapp.com/attachments/809363224663031829/809734218103259146/leaderboards.png"

# Sets aliases for the leaderboard command
leaderboard_alias: ['lb', 'leader', 'rankings']


# Rank Config
# Sets aliases for the rank command
rank_alias: ['r', 'level', 'l', 'stats', 'xp', 'progress']


# Embed Config
# Rank Embed Colour | Must Be Hex Notation
rank_embed_colour: 0xFFFFFF

# Leaderboard Embed Colour | Must Be Hex Notation
leaderboard_embed_colour: 0xFFFFFF

# Embed Colour | Must Be Hex Notation
embed_colour: 0xFFFFFF

# Error Embed Colour | Must Be Hex Notation
error_embed_colour: 0xFF0000

# Success Embed Colour | Mist Be Hex Notation
success_embed_colour: 0x00FF00


# Help Config
# True/False - <prefix>help command
help_command: True


