# ======================================================================================
#                             WELCOME TO THE CONFIG
#                                      FOR
#                                 MODERN LEVELS
# ======================================================================================
# NOTE: BOT_TOKEN & MONGO CLIENT DETAILS ARE STORED IN THE .env FILE!
# The prefix for the bots commands
Prefix: "!"

# Set what the bot is currently playing
bot_status_text: "[!] | Modern Levels"

# IDLE, DND, ONLINE, OFFLINE
bot_activity: online

# The ID of the user who owns this bot (In most cases, that'll be you)
bot_owner_id: 512760269764820993

# Disable / Enable the bot from sending the private message when joining a guild (True/False)
private_message: True

# Rank Card Generator (Vacefron / Canvacord) - Beware! Canvacord will be slightly slower, and will use your roles colour as your xp colour meaning you cannot have a custom xp colour!
generator: Vacefron


# ======================================================================================
#                                     XP
# ======================================================================================
# How much XP is required per level (e.g - xp_per_level: 10 = Level 1 would require 10 xp to level up. Level 2 would require 20 xp to level up)
xp_per_level: 100

# What level is required to create a clan (*requires clan system addon*)
level_for_clan: 1

# ======================================================================================
#                                   VOCAL XP
# ======================================================================================
# NOTE: REQUIRES VOCAL SYSTEM ADDON! DOWNLOAD FROM GITHUB REPOSITORY

# How long until a user is granted their xp (e.g 60 = 1 minute)
time_for_xp: 60

# How much xp a user will receive when in a voice channel and has been in for time_for_xp
xp_per_time: 6

# ======================================================================================
#                                  LEADERBOARD
# ======================================================================================
# Amount of users to be shown on the leaderboard
leaderboard_amount: 10

# Sets aliases for the leaderboard command
leaderboard_alias: ['lb', 'leader', 'rankings']


# ======================================================================================
#                                   RANK
# ======================================================================================
# Sets aliases for the rank command
rank_alias: ['r', 'level', 'l', 'stats', 'xp', 'progress']

# Sends a ping to the user that levelled up
level_up_ping: False


# ======================================================================================
#                                   EMBED
# ======================================================================================
# Rank Embed Colour | Must Be Hex Notation
rank_embed_colour: 0x4863A0

# Leaderboard Embed Colour | Must Be Hex Notation (Replace # with 0x)
leaderboard_embed_colour: 0xffffff

# Embed Colour | Must Be Hex Notation
embed_colour: 0xffffff

# Error Embed Colour | Must Be Hex Notation
error_embed_colour: 0x4863A0

# Success Embed Colour | Must Be Hex Notation
success_embed_colour: 0x4863A0


# ======================================================================================
#                                     HELP
# ======================================================================================
# True/False - <prefix>help command
# NOTE: REQUIRES Extras+ ADDON!
help_command: True


# ======================================================================================
#                                    THE END
# ======================================================================================



