# ======================================================================================
#                             WELCOME TO THE CONFIG
#                                      FOR
#                                 MODERN LEVELS
# ======================================================================================
# NOTE: BOT_TOKEN & MONGO CLIENT DETAILS ARE STORED IN THE .env FILE!
# The prefix for the bots commands
Prefix: "!"

# Set what the bot is currently playing
bot_status_text: "[!] | Modern Levels"

# IDLE, DND, ONLINE, OFFLINE
bot_activity: online


# ======================================================================================
#                                     XP
# ======================================================================================
# How much XP is required per level (e.g - xp_per_level: 10 = Level 1 would require 10 xp to level up. Level 2 would require 20 xp to level up)
xp_per_level: 100


# ======================================================================================
#                                  LEADERBOARD
# ======================================================================================
# Amount of users to be shown on the leaderboard
leaderboard_amount: 10

# Sets the image that displays on the leaderboard embed
leaderboard_image: "https://cdn.discordapp.com/attachments/812895798496591882/825363205853151252/ML_1.png"

# Sets aliases for the leaderboard command
leaderboard_alias: ['lb', 'leader', 'rankings']


# ======================================================================================
#                                   RANK
# ======================================================================================
# Sets aliases for the rank command
rank_alias: ['r', 'level', 'l', 'stats', 'xp', 'progress']

# Sends a ping to the user that levelled up
level_up_ping: True


# ======================================================================================
#                                   EMBED
# ======================================================================================
# Rank Embed Colour | Must Be Hex Notation
rank_embed_colour: 0x4863A0

# Leaderboard Embed Colour | Must Be Hex Notation (Replace # with 0x)
leaderboard_embed_colour: 0x4863A0

# Embed Colour | Must Be Hex Notation
embed_colour: 0x4863A0

# Error Embed Colour | Must Be Hex Notation
error_embed_colour: 0x4863A0

# Success Embed Colour | Must Be Hex Notation
success_embed_colour: 0x4863A0


# ======================================================================================
#                                     HELP
# ======================================================================================
# True/False - <prefix>help command
help_command: True


# ======================================================================================
#                                    THE END
# ======================================================================================



