# ======================================================================================
#                                 SEASONAL CONFIG
# ======================================================================================

# Enables / Disabled seasonal mode. -- Seasonal Mode is where when a time of year arrives, such as christmas, halloween, summer etc; users can receive bonus
# XP
seasonal_mode: True

# The amount of extra xp a user receives
bonus_xp: 1.5


# ======================================================================================
#                                    Dates
# ======================================================================================

# When do you expect to end the easter event? (DAY MONTH - Don't worry about year, it's already handled for you)
easter_end_date: "May 1st"

# When do you expect to end the summer event? (DAY MONTH - Don't worry about year, it's already handled for you)
summer_end_date: "August 1st"

# When do you expect to end the summer event? (DAY MONTH - Don't worry about year, it's already handled for you)
halloween_end_date: "November 1st"

# When do you expect to end the summer event? (DAY MONTH - Don't worry about year, it's already handled for you)
christmas_end_date: "January 1st"


# ======================================================================================
#                                    THE END
# ======================================================================================



