# ======================================================================================
#                             WELCOME TO THE CONFIG
#                                      FOR
#                                THE VOCAL ADDON
# ======================================================================================

# How many minutes until someone can earn XP in a VC (Repeats every x minutes)
# Default: 5 minutes (300 seconds)
waiting_time: 300

# How much XP is earned per waiting_time
# Default: 100 XP
xp_per_time: 100

